export {default as Home} from './Home'
export {default as Signin} from './SignIn'
export {default as Signup} from './Signup'
export {default as Account} from './Account'
export {default as CoinPage} from './CoinPage'